version: '3.4'
services:
  db:
    image: stsiwo/sts-blog-db 
  webserver:
    image: stsiwo/sts-blog-spa
    ports: 
      - "80:80"
    depends_on:
      - api1
  api1:
    image: stsiwo/sts-blog-api
    ports: 
      - "5000:5000"
    depends_on:
      - db
