version: '3'
services:
  spa:
  api1:
  web-server: 
    image: nginx
    volumes:
      - "$PWD/WebServer/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports: 
      - "8080:80"
  # db: in-memory in dev
