version: '3.4'
services:
  db:
    # using latest (8.x.x) mysql cause below error:
    # mbind: Operation not permitted
    # workaround: https://github.com/docker-library/mysql/issues/303
    # - use older version
    image: mysql:5.7.28
    volumes:
     - '$PWD/Db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/'
  webserver:
    build: 
      context: './Spa'
      target: staging
    volumes:
      - "$PWD/WebServer/dev.stsiwo.com:/etc/nginx/conf.d/default.conf:ro"
      - "$PWD/WebServer/api.stsiwo.com:/etc/nginx/conf.d/api.stsiwo.com:ro"
    ports: 
      - "80:80"
    depends_on:
      - api1
  api1:
    build: 
      context: './Api1'
      target: staging 
    environment:
      - FLASK_ENV=staging
      - FLASK_APP=./run.py
    env_file:
      - "./Api1/.env.staging"
    volumes:
      - "/app/env"
      - "/app/tests"
    ports: 
      - "5000:5000"
    depends_on:
      - db
