version: '3.4'
services:
  db:
    image: stsiwo/sts-blog-db 
    volumes:
      - db-data-staging-storage:/var/lib/mysql 
      - db-logging-staging-storage:/var/log/mysql
  webserver:
    image: stsiwo/sts-blog-spa
    ports: 
      - "80:80"
    volumes:
      - webserver-logging-staging-storage:/var/log/nginx
    depends_on:
      - api1
  api1:
    image: stsiwo/sts-blog-api
    ports: 
      - "5000:5000"
    volumes:
      - api-logging-staging-storage:/var/log/sts-blogs-api
    depends_on:
      - db
volumes:
  db-data-staging-storage:
  db-logging-staging-storage:
  api-logging-staging-storage:
  webserver-logging-staging-storage:
