version: '3.4'
services:
  db:
    environment: 
      MYSQL_DATABASE: sts_blogs_dev
      MYSQL_USER: sts
      MYSQL_PASSWORD: sts1551@IWO
      MYSQL_ROOT_PASSWORD: sts1551@IWO
  api1:
    # when you want to set False as a env var, don't assign any value to the env such as ' (quote) or " (double quote)
    # Flask recognize it has value and give True to the config property 
    environment:
      - FLASK_ENV=staging
      - FLASK_APP=./run.py
      - DEBUG=1
      - HOST_NAME=http://dev.api.stsiwo.com
      - JWT_COOKIE_SECURE=
      - JWT_COOKIE_DOMAIN=stsiwo.com
      - JWT_SECRET_KEY="keepThisSecret"
      - JWT_ACCESS_TOKEN_EXPIRES=1000
      - JWT_REFRESH_TOKEN_EXPIRES=1800
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://sts:sts1551@IWO@db:3306/sts_blogs_dev
      - SECRET_KEY=mustBeSecretl
      - SQLALCHEMY_ECHO='1'
      - UPLOAD_FOLDER=temp/uploads
      - SIGNER_SECRET_KEY=keepThisSecret
      - CLIENT_SPA_URL=http://dev.stsiwo.com
