version: '3.4'
services:
  webserver:
    build: 
      context: './Spa'
      target: staging
    environment:
      - NODE_ENV=staging 
    env_file:
      - "./Spa/.env.prod"
    volumes:
      - "$PWD/WebServer/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports: 
      - "80:80"
