version: '3.4'
services:
  db:
    image: stsiwo/sts-blog-db 
    volumes:
      - db-staging-storage:/var/lib/mysql 
      - db-logging-storage:/var/log/mysql
  webserver:
    image: stsiwo/sts-blog-spa
    ports: 
      - "80:80"
    depends_on:
      - api1
  api1:
    image: stsiwo/sts-blog-api
    volumes:
      - api-migration-storage:/migrations/
    ports: 
      - "5000:5000"
    depends_on:
      - db
volumes:
  db-staging-storage:
  db-logging-storage:
  api-migration-storage:
