version: '3.4'
services:
  db:
    # using latest (8.x.x) mysql cause below error:
    # mbind: Operation not permitted
    # workaround: https://github.com/docker-library/mysql/issues/303
    # - use older version
    image: mysql:5.7.28
    environment: 
      MYSQL_DATABASE: sts_blogs_dev
      MYSQL_USER: sts
      MYSQL_PASSWORD: sts1551@IWO
      MYSQL_ROOT_PASSWORD: sts1551@IWO
    ports:
     - "3307:3306"
    volumes:
     - '$PWD/Db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/'

  #  spa:
  #    #image: spa:dev
  #    build: 
  #      context: './Spa'
  #      target: development
  #    volumes:
  #      - "/app/node_modules"
  #      - "$PWD/Spa/:/app"
  #    ports: 
  #      - "80:8080"
  api1:
    build: 
      context: './Api1'
      target: development
    # image: api1:dev
    volumes:
      - "$PWD/Api1/:/app"
    env_file:
      - './Api1/.env.development'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=./run.py
    ports: 
      - "5000:5000"
    depends_on:
      - db
#  web-server: 
#    image: nginx
#    volumes:
#      - "$PWD/WebServer/default.conf:/etc/nginx/conf.d/default.conf:ro"
#    ports: 
#      - "8080:80"
  # db: in-memory in dev
