version: 2
jobs:
  #   build:
  #     docker:
  #       - image: circleci/node:10.16.3    
  #     steps:
  #       - checkout
  #       - run: 
  #           name: Install Dependencies 
  #           working_directory: ./Spa
  #           command: |
  #             ls -al 
  #             npm install
  #       - restore_cache:
  #           keys:
  #             - dep1-{{ checksum "./Spa/package-lock.json" }}
  #       - run:
  #           name: Run Test
  #           working_directory: ./Spa
  #           command: |
  #          npx jest tests/
  build:
    docker:
      - image: circleci/python:3.6.8-stretch-browsers
    steps:
      - checkout # need to exclude env and migration folder. oh already excluded !! nice
      - run:  # this works only local, don't include sensitive info inside this file. when testing in circleci server, remove this 'run'
          name: Set Env Vars 
          working_directory: ./Api1
          command: |
            export JWT_COOKIE_SECURE=False
            export JWT_SECRET_KEY=keepThisbSecret
            export SQLALCHEMY_DATABASE_URI=sqlite:////tmp/api1.db
            export TESTING=True
            export SECRET_KEY=mustBeSecretl
            export SQLALCHEMY_ECHO=True
            export UPLOAD_FOLDER=temp/uploads 
            export SIGNER_SECRET_KEY=keepThisSecret
            export CLIENT_SPA_URL=http://localhost
      - run: 
          name: Install Dependencies 
          working_directory: ./Api1
          command: |
            ls -al 
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - restore_cache:
          keys:
            - dep1-{{ checksum "./Api1/requirements.txt" }}
      - run:
          name: Setup SQLight database 
          working_directory: ./Api1
          command: |
            rm -r ./migrations
            . venv/bin/activate
            export FLASK_ENV=TESTING
            export FLASK_APP=./run.py
            flask db init
            flask db migrate
            flask db upgrade
      - run:
          name: Run Test
          working_directory: ./Api1
          command: |
            . venv/bin/activate
            python -m pytest 
